version: '3'

set: [pipefail]

includes:
  crypto:
    taskfile: crypto.task.yaml
    internal: true

  nervo-server:
    taskfile: nervobot.vault.task.yml
    vars:
      KEY_NAME: nervo-server.config.yaml

  probiot-t1000:
    taskfile: nervobot.vault.task.yml
    vars:
      KEY_NAME: probiot-t1000.config.yaml

  groot:
    taskfile: nervobot.vault.task.yml
    vars:
      KEY_NAME: groot.config.yaml

tasks:

  get_prod_host:
    cmds:
      - task: crypto:decrypt
        vars:
          BASE_PATH: prod
          KEY_NAME: host

  get_prod_user:
    cmds:
      - task: crypto:decrypt
        vars:
          BASE_PATH: prod
          KEY_NAME: user

  get_prod_pass:
    cmds:
      - task: crypto:decrypt
        vars:
          BASE_PATH: prod
          KEY_NAME: pass

  get_docker_email:
    cmds:
      - task: crypto:decrypt
        vars:
          BASE_PATH: docker
          KEY_NAME: email

  get_docker_user:
    cmds:
      - task: crypto:decrypt
        vars:
          BASE_PATH: docker
          KEY_NAME: user

  get_docker_pass:
    cmds:
      - task: crypto:decrypt
        vars:
          BASE_PATH: docker
          KEY_NAME: pass

  get_github_token:
    cmds:
      - task: crypto:decrypt
        vars:
          BASE_PATH: github
          KEY_NAME: token

  get_cloudflare_api_token:
    cmds:
      - task: crypto:decrypt
        vars:
          BASE_PATH: cloudflare
          KEY_NAME: api_token

  get_cloudflare_account_id:
    cmds:
      - task: crypto:decrypt
        vars:
          BASE_PATH: cloudflare
          KEY_NAME: account_id

  get_test:
    cmds:
      - task: crypto:decrypt
        vars:
          BASE_PATH: test
          KEY_NAME: test

  get_test2:
    cmds:
      - task: crypto:decrypt
        vars:
          BASE_PATH: test
          KEY_NAME: test2
