version: '3'

vars:
  CONFIGS: pvc.k statefulset.k
  BUILD_DIR: build

tasks:
  default:
    cmds:
      - task --list-all

  generate_config_maps:
    cmds:
      - kubectl create configmap nervobot-config --from-file=config.yaml --dry-run=client -o yaml > {{ .BUILD_DIR }}/configmap.yaml

  generate_manifests:
    cmds:
      - for: { var: CONFIGS }
        cmd: kcl {{ .ITEM }} > {{ .BUILD_DIR }}/{{ .ITEM }}.yaml

  generate:
    cmds:
      - rm -rf {{ .BUILD_DIR }}
      - mkdir -p {{ .BUILD_DIR }}
      - task: generate_config_maps
      - task: generate_manifests


  apply:
    cmds:
      - task: generate
      - kubectl apply -f {{ .BUILD_DIR }}

  delete:
    cmds:
      - task: generate
      - kubectl delete -f {{ .BUILD_DIR }}

  describe:
    cmds:
      - kubectl describe pod probiot-t1000-0
