import '../../hazmat/justfile'

PROVISION_TMP_DIR := "../provision/tmp"
BOOTSTRAP_TMP_DIR := "tmp"

BOOSTRAP_TF_VARS := BOOTSTRAP_TMP_DIR + "/security.tfvars.json"
GITHUB_TOKEN_FILE := PROVISION_TMP_DIR + "/github_token.txt"

bootstrap:
    mkdir -p {{PROVISION_TMP_DIR}}
    mkdir -p {{BOOTSTRAP_TMP_DIR}}

    @just save_tf_security_vars {{BOOSTRAP_TF_VARS}}
    @just save_github_token {{GITHUB_TOKEN_FILE}}
    terraform init -var-file={{BOOSTRAP_TF_VARS}}
    terraform apply -auto-approve -var-file={{BOOSTRAP_TF_VARS}}
