version: '3'

includes:
  void_sentinel:
    taskfile: void_sentinel/Taskfile.yml
    dir: void_sentinel

tasks:
  default:
    cmds:
      - task --list-all

  local_tmp_clean_up:
    cmds:
      - rm -rf {{.LOCAL_TMP_DIR}}/**
