cluster_name := "nervoset"

k8s_utils_install:
    sudo snap install helm --classic
    sudo snap install kubectl --classic

k3d_install:
    sudo snap install helm --classic
    curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

k3d_cluster_deploy:
    k3d cluster create {{cluster_name}} -p "80:80@loadbalancer" -p "443:443@loadbalancer" --agents 1 || true

k3d_delete:
    k3d cluster delete {{cluster_name}} || true

qdrant_install:
    helm repo add qdrant https://qdrant.to/helm || true
    helm repo update
    helm install qdrant qdrant/qdrant --set ingress.enabled=true

qdrant_uninstall:
    helm uninstall qdrant