version: '3'

set: [pipefail]

vars:
  REGISTRY: 'cypherkitty'
  REPOSITORY: 'nervoset'
  APP_VERSION: '0.1'

includes:
  hazmat:
    taskfile: hazmat/Taskfile.yml
    dir: hazmat
  deployment:
    taskfile: deployment/Taskfile.yml
    dir: deployment
  k8s:
    taskfile: k8s/Taskfile.yml
    dir: k8s
    vars:
      REGISTRY: '{{.REGISTRY}}'
      REPOSITORY: '{{.REPOSITORY}}'
      VERSION: '{{.APP_VERSION}}'
      INFRA: '{{.INFRA}}'

tasks:
  default:
    cmds:
      - task --list-all

  auth:
    cmds:
      - task hazmat:void_sentinel:auth

  img_name:
    requires:
      vars:
        - REGISTRY
        - REPOSITORY
        - K8S_APP_NAME
        - APP_VERSION
        - INFRA
    cmds:
      - |
        ./gradlew \
            -Pinfra={{.INFRA}} \
            -Pregistry={{.REGISTRY}} \
            -Prepository={{.REPOSITORY}} \
            -Pk8sAppName={{.K8S_APP_NAME}} \
            -PappVersion={{.APP_VERSION}} \
            imgName -q

  completions:
    cmds:
      - alias k=kubectl

      - kubectl completion bash > ~/.kube/completion.bash
      - source ~/.kube/completion.bash

      - complete -o default -F __start_kubectl k

      - k3d completion bash > ~/.k3d/completion.bash
      - source ~/.k3d/completion.bash

      - helm completion bash > ~/.helm/completion.bash
      - source ~/.helm/completion.bash

      - mkdir -p ~/.task/
      - curl --silent https://raw.githubusercontent.com/go-task/task/main/completion/bash/task.bash > ~/.task/completion.bash
      - source ~/.task/completion.bash
    interactive: true