# https://k3d.io/v5.6.0/usage/configfile/#config-options

apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: nervoset
servers: 1
agents: 1
network: k3d-nervoset

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer

