target_dir := "target"
dependencies_dir := target_dir + "/nervoset_dependencies"
nervo_core_dir := dependencies_dir + "/nervo_core"

probiot_t1000_dir := dependencies_dir + "/probiot_t1000"
r2d2_dir := dependencies_dir + "/r2d2"

clean:
    cargo clean

prepare_dependencies:
    # Create core project structure
    mkdir -p {{dependencies_dir}}
    mkdir -p {{nervo_core_dir}}

    mkdir -p {{probiot_t1000_dir}}
    mkdir -p {{r2d2_dir}}

    # copy cargo.toml files
    cp Cargo.toml {{dependencies_dir}}/Cargo.toml
    cp nervo_core/Cargo.toml {{nervo_core_dir}}/Cargo.toml

    cp probiot_t1000/Cargo.toml {{probiot_t1000_dir}}/Cargo.toml
    cp r2d2/Cargo.toml {{r2d2_dir}}/Cargo.toml

    # create src files
    mkdir -p {{nervo_core_dir}}/src
    mkdir -p {{probiot_t1000_dir}}/src
    mkdir -p {{r2d2_dir}}/src

    echo "fn main() {}" > {{nervo_core_dir}}/src/lib.rs
    echo "fn main() {}" > {{probiot_t1000_dir}}/src/main.rs
    echo "fn main() {}" > {{r2d2_dir}}/src/main.rs

docker_test: prepare_dependencies
    docker compose run test

docker_probiot_t1000_build: prepare_dependencies
	docker compose build probiot_t1000

docker_probiot_t1000_run: docker_probiot_t1000_build
    docker compose up probiot_t1000

docker_probiot_t1000_run_daemon: docker_probiot_t1000_build
    docker compose up -d probiot_t1000

docker_probiot_t1000_down:
    docker compose down probiot_t1000

docker_r2d2_build: prepare_dependencies
	docker compose build r2d2

docker_r2d2_run: docker_r2d2_build
    docker compose up r2d2

docker_r2d2_run_daemon: docker_r2d2_build
    docker compose up -d r2d2

docker_r2d2_down:
    docker compose down r2d2

docker_system_clean_up:
    docker system prune -a