version: '3'

vars:
  REGISTRY: 'cypherkitty'

includes:
  probiot:
    taskfile: .task/docker.yml
    vars:
      APP_NAME: 'probiot_t1000'
      VERSION: '0.1'

  jarvis:
    taskfile: .task/docker.yml
    vars:
      APP_NAME: 'r2d2'
      VERSION: '0.1'

  groot:
    taskfile: .task/docker.yml
    vars:
      APP_NAME: 'groot'
      VERSION: '0.1'

  walle:
    taskfile: .task/docker.yml
    vars:
      APP_NAME: 'walle'
      VERSION: '0.1'

  nervo_server:
    taskfile: .task/docker.yml
    vars:
      APP_NAME: 'nervo_server'
      VERSION: '0.1'
      HOST_PORT: '3000'
      DOCKER_PORT: '3000'

tasks:
  default:
    cmds:
      - task --list-all
