version: '3'

set: [pipefail]

includes:
  base_vars: .task/base.vars.yml
  common: .task/common.yml

  docker_probiot:
    taskfile: .task/docker.yml
    requires:
      vars:
        - INFRA #'dev' or 'prod'
    vars:
      APP_NAME: 'probiot_t1000'
      K8S_APP_NAME: 'probiot-t1000'
      VERSION: '{{.APP_VERSION}}'
      IMAGE_NAME:
        sh: task img_name K8S_APP_NAME={{.K8S_APP_NAME}} INFRA={{.INFRA}}

  docker_groot:
    taskfile: .task/docker.yml
    requires:
      vars:
        - INFRA #'dev' or 'prod'
    vars:
      APP_NAME: 'groot'
      K8S_APP_NAME: 'groot'
      VERSION: '{{.APP_VERSION}}'
      IMAGE_NAME:
        sh: task img_name K8S_APP_NAME={{.K8S_APP_NAME}} INFRA={{.INFRA}}

  docker_nervo_server:
    taskfile: .task/docker.yml
    requires:
      vars:
        - INFRA #'dev' or 'prod'
    vars:
      APP_NAME: 'nervo_server'
      K8S_APP_NAME: "nervo-server"
      VERSION: '{{.APP_VERSION}}'
      HOST_PORT: '3000'
      DOCKER_PORT: '3000'
      IMAGE_NAME:
        sh: task img_name K8S_APP_NAME={{.K8S_APP_NAME}} INFRA={{.INFRA}}

tasks:
  default:
    cmds:
      - task --list-all

  img_name:
    requires:
      vars:
        - K8S_APP_NAME
        - INFRA
    cmds:
      - |
        cd ../infra && ./gradlew \
            -Pinfra={{.INFRA}} \
            -Pregistry={{.REGISTRY}} \
            -Prepository={{.REPOSITORY}} \
            -Pk8sAppName={{.K8S_APP_NAME}} \
            -PappVersion={{.APP_VERSION}} \
            --quiet \
            imgName

  build_nervo_web_component:
    requires:
      vars:
        - APP_TYPE
    vars:
      NERVO_WASM_DIR: 'app/nervo_wasm'
      NERVO_WEB_DIR: 'nervo-web'
    cmds:
      - cd {{.NERVO_WASM_DIR}} && wasm-pack build

      - rm -rf {{.NERVO_WEB_DIR}}/pkg
      - rm -rf {{.NERVO_WEB_DIR}}/dist

      - mkdir -p {{.NERVO_WEB_DIR}}/pkg
      - cp -r {{.NERVO_WASM_DIR}}/pkg {{.NERVO_WEB_DIR}}
      - "cd {{.NERVO_WEB_DIR}} && npm install && VITE_APP_TYPE={{.APP_TYPE}} npm run build:lib"

  nervo_web_build:
    requires:
      vars:
        - APP_TYPE
    vars:
      NERVO_WASM_DIR: 'app/nervo_wasm'
      NERVO_WEB_DIR: 'nervo-web'
    cmds:
      - cd {{.NERVO_WASM_DIR}} && wasm-pack build

      - rm -rf {{.NERVO_WEB_DIR}}/pkg
      - rm -rf {{.NERVO_WEB_DIR}}/dist

      - mkdir -p {{.NERVO_WEB_DIR}}/pkg
      - cp -r {{.NERVO_WASM_DIR}}/pkg {{.NERVO_WEB_DIR}}
      - "cd {{.NERVO_WEB_DIR}} && npm install && VITE_APP_TYPE={{.APP_TYPE}} npm run build:app"

  nervo_web_run:
    requires:
      vars:
        - SERVER_PORT
        - APP_TYPE
    cmds:
      - task: nervo_web_build
      - "cd nervo-web && VITE_SERVER_PORT={{.SERVER_PORT}} VITE_APP_TYPE={{.APP_TYPE}} npm run dev"

  test:
    cmds:
      - task: common:base_build
      - docker run --rm {{.BASE_IMAGE}} cargo test --release

  docker_push:
    requires:
      vars:
        - INFRA #'dev' or 'prod'
    cmds:
      - task: docker_groot:push
      - task: docker_probiot:push
      - task: docker_jarvis:push
      - task: docker_nervo_server:push