[workspace]

resolver = "2"

members = [
    "groot",
    "nervo_core",
    "probiot_t1000",
    "r2d2",
    "nervo_server"
]

[workspace.dependencies]
# Error handling
thiserror = "1.0"
anyhow = "1.0"

config = { version = "0.14", features = ["yaml"] }

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3" }

# Json
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_derive = "1.0.188"

# LLM
async-openai = "0.20.0"
