version: '3'

includes:
  k3d_dev:
    taskfile: k3d.task.yml
    vars:
      CLUSTER_NAME: '{{.CLUSTER_NAME | default "nervoset-dev"}}'
      K3D_CONFIG: "k3d/k3d.dev.yaml"
  k3d_prod:
    taskfile: k3d.task.yml
    vars:
      CLUSTER_NAME: '{{.CLUSTER_NAME | default "nervoset-prod"}}'
      K3D_CONFIG: "k3d/k3d.prod.yaml"

  vector_db: vector_db.task.yml

tasks:
  default:
    cmds:
      - task --list-all

  k3d_within_docker:
    cmds:
      - |-
        docker run -it --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v /usr/bin/docker:/usr/bin/docker \
          -v /usr/local/bin/k3d:/usr/local/bin/k3d \
          ubuntu:latest \
          bash
