version: '3'

includes:
  k3d_dev:
    taskfile: k3d/Taskfile.yml
    dir: k3d
    vars:
      K3D_CONFIG: "k3d.dev.yaml"
      K3D_HTTP_PORT:
        sh: shuf -i 8000-9000 -n 1
      K3D_HTTPS_PORT:
        sh: shuf -i 9000-10000 -n 1

  k3d_prod:
    taskfile: k3d/Taskfile.yml
    dir: k3d
    vars:
      K3D_CONFIG: "k3d.prod.yaml"

  docker_registry:
    taskfile: docker-registry/Taskfile.yml

  vector_db:
    taskfile: db/vector_db/Taskfile.yml

tasks:
  default:
    cmds:
      - task --list-all

  # k3d installation has to be done outside of this task
  infra_dev:
    vars:
      K8S_CLUSTER_NAME:
        sh: echo $(whoami)-nervoset-dev
    cmds:
      - task -t ../Taskfile.yml auth

      - task: docker_registry:docker_login

      # deploy k8s cluster with k3d
      - task: k3d_dev:k8s_deploy
        vars:
          CLUSTER_NAME: '{{.K8S_CLUSTER_NAME}}'

      # setup persistent volume for k8s
      - kubectl apply -f kube

      # setup docker registry authentication in k8s
      - task: docker_registry:setup_docker_registry

      # deploy qdrant
      - task: vector_db:qdrant_deploy

      - task -t ../Taskfile.yml hazmat:void_sentinel:clean_up

  infra_dev_delete:
    vars:
      K8S_CLUSTER_NAME:
        sh: echo $(whoami)-nervoset-dev
    cmds:
      - task: k3d_dev:k8s_delete
        vars:
          CLUSTER_NAME: '{{.K8S_CLUSTER_NAME}}'

  k3d_within_docker:
    cmds:
      - |-
        docker run -it --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v /usr/bin/docker:/usr/bin/docker \
          -v /usr/local/bin/k3d:/usr/local/bin/k3d \
          ubuntu:latest \
          bash
