version: '3'

vars:
  QDRANT_BACKUP_DIR: "build/qdrant_backup"
  BACKUP_MANAGER_POD_NAME: "qdrant-backup-manager-0"
  QDARNT_SERVER_URL: "http://qdrant.default.svc.cluster.local:6333"

tasks:
  qdrant_restore_from_backup:
    requires:
      vars:
        - DATE
    vars:
      PROBIO_COLLECTION: "probio_collection"
      PROBIO_COLLECTION_SNAPSHOT: "{{.PROBIO_COLLECTION}}-3563913780311279-2024-06-24-23-21-27.snapshot"

    cmds:
      - task: download_backup_repo
      - task: rebuild_backup_manager

      # https://medium.com/@nnilesh7756/copy-directories-and-files-to-and-from-kubernetes-container-pod-19612fa74660
      - sleep 30
      - task: copy_backup
      - task: restore

  copy_backup:
    cmds:
      - |-
        kubectl cp \
          {{.QDRANT_BACKUP_DIR}}/{{.DATE}}/{{.PROBIO_COLLECTION_SNAPSHOT}} \
          {{.BACKUP_MANAGER_POD_NAME}}:/qdrant-backup/{{.PROBIO_COLLECTION_SNAPSHOT}}

  restore:
    cmds:
      - kubectl exec -ti {{.BACKUP_MANAGER_POD_NAME}} -- sh /backup-tools/restore.sh

  download_backup_repo:
    cmds:
      - |-
        if [ -d "{{.QDRANT_BACKUP_DIR}}" ]; then
          mkdir -p {{.QDRANT_BACKUP_DIR}}
          cd {{.QDRANT_BACKUP_DIR}}
          git pull
        else
          git clone https://github.com/nervoset/qdrant_backup.git {{.QDRANT_BACKUP_DIR}}
        fi 

  rebuild_backup_manager:
    cmds:
      - task: delete_backup_manager
      - task: generate_build_tools

      - kubectl delete -f build/configmap.yaml || true
      - kubectl apply -f build/configmap.yaml

      - cmd: apply_backup_manager

  generate_build_tools:
    cmds:
      - |
        kubectl create configmap \
        qdrant-backup-manager-config \
        --from-file=backup-tools \
        --dry-run=client \
        -o yaml > \
        build/configmap.yaml

  apply_backup_manager:
    cmds:
      - kubectl apply -f qdrant-backup-manager.yaml
      - kubectl wait --for=jsonpath='{.status.phase}'=Running pod/{{.BACKUP_MANAGER_POD_NAME}} --timeout=60s

  delete_backup_manager:
    cmds:
      - kubectl delete -f qdrant-backup-manager.yaml || true
      - kubectl wait --for=delete pod/{{.BACKUP_MANAGER_POD_NAME}} --timeout=180s
