version: '3'

tasks:
  qdrant_deploy:
    cmds:
      - helm repo add qdrant https://qdrant.github.io/qdrant-helm || true
      - helm repo update
      - helm upgrade -i qdrant qdrant/qdrant

  qdrant_delete:
    cmds:
      - helm uninstall qdrant
