version: '3'

tasks:
  qdrant_deploy:
    cmds:
      - helm repo add qdrant https://qdrant.github.io/qdrant-helm || true
      - helm repo update
      - helm upgrade -i qdrant qdrant/qdrant --version 1.11.0
      - kubectl wait --for=jsonpath='{.status.phase}'=Running pod/qdrant-0 --timeout=180s

  qdrant_delete:
    cmds:
      - helm uninstall qdrant || true
      - kubectl wait --for=delete pod/qdrant-0 --timeout=180s || true
      - kubectl delete pvc qdrant-storage-qdrant-0 || true
