apiVersion: v1
kind: PersistentVolume
metadata:
  name: nervoset-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/nervoset/data" # see k3d/k3d.*.yaml volumes