[package]
name = "nervo-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true

serde.workspace = true
serde_json.workspace = true
serde_derive.workspace = true
wasm-bindgen = "0.2.84"

enum-iterator.workspace = true
