version: '3'

set: [pipefail]

requires:
  vars:
    - CONFIGS
    - K8S_APP_NAME
    - IMAGE_NAME

vars:
  BUILD_DIR: build

tasks:
  default:
    cmds:
      - task --list-all

  print_vars:
    cmds:
      - echo configs {{.CONFIGS}}
      - echo app name {{.K8S_APP_NAME}}
      - echo img name {{.IMAGE_NAME}}

  deliver_config:
    cmds:
      - task -t ../../Taskfile.yml hazmat:void_sentinel:vault:{{.K8S_APP_NAME}}:get_config INFRA={{.INFRA}} > {{.BUILD_DIR}}/config.yaml

  generate_config_maps:
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - task: deliver_config
      - |
        kubectl create configmap \
          {{.K8S_APP_NAME}}-config \
          --from-file={{.BUILD_DIR}}/config.yaml \
          --dry-run=client -o yaml > \
          {{ .BUILD_DIR }}/configmap.yaml
      - rm -rf {{.BUILD_DIR}}/config.yaml

  generate_manifests:
    requires:
      vars:
        - IMAGE_NAME
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - for: { var: CONFIGS }
        cmd: kcl {{ .ITEM }} -D imageName="{{.IMAGE_NAME}}" > {{ .BUILD_DIR }}/{{ .ITEM }}.yaml

  generate:
    cmds:
      - rm -rf {{ .BUILD_DIR }}
      - mkdir -p {{ .BUILD_DIR }}
      - task: generate_config_maps
      - task: generate_manifests

  apply:
    cmds:
      - task: generate
      - kubectl apply -f {{ .BUILD_DIR }}

  delete:
    cmds:
      - task: generate
      - kubectl delete -f {{ .BUILD_DIR }}

  describe:
    cmds:
      - kubectl describe pod probiot-t1000-0
