DOCKER_REGISTRY_URL := "https://index.docker.io/v1/"

# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
k8s_setup_docker_registry:
    kubectl create secret docker-registry docker-registry-secret \
      --docker-server={{DOCKER_REGISTRY_URL}} \
      --docker-username=${DOCKER_REGISTRY_USER} \
      --docker-password=${DOCKER_REGISTRY_PASS} \
      --docker-email={DOCKER_REGISTRY_EMAIL} || true

