version: '3'

set: [pipefail]

includes:
  probiot:
    taskfile: app.task.yml
    dir: probiot
    vars:
      K8S_APP_NAME: 'probiot'
      APP_NAME: 'jarvis'
      CONFIGS: pvc.k statefulset.k
      IMAGE_NAME:
        sh: task img_name REGISTRY={{.REGISTRY}} REPOSITORY={{.REPOSITORY}} K8S_APP_NAME={{.APP_NAME}} APP_VERSION={{.APP_VERSION}} INFRA={{.INFRA}}

  w3a:
    taskfile: app.task.yml
    dir: w3a
    vars:
      K8S_APP_NAME: 'w3a'
      APP_NAME: 'jarvis'
      CONFIGS: pvc.k statefulset.k
      IMAGE_NAME:
        sh: task img_name REGISTRY={{.REGISTRY}} REPOSITORY={{.REPOSITORY}} K8S_APP_NAME={{.APP_NAME}} APP_VERSION={{.APP_VERSION}} INFRA={{.INFRA}}

  groot:
    taskfile: app.task.yml
    dir: groot
    vars:
      K8S_APP_NAME: 'groot'
      APP_NAME: 'groot'
      CONFIGS: pvc.k statefulset.k
      IMAGE_NAME:
        sh: task img_name REGISTRY={{.REGISTRY}} REPOSITORY={{.REPOSITORY}} K8S_APP_NAME={{.K8S_APP_NAME}} APP_VERSION={{.APP_VERSION}} INFRA={{.INFRA}}

  nervo_server:
    taskfile: app.task.yml
    dir: nervo-server
    vars:
      K8S_APP_NAME: "nervo-server"
      APP_NAME: "nervo_server"
      CONFIGS: pvc.k statefulset.k service.k ingress.k
      IMAGE_NAME:
        sh: task img_name REGISTRY={{.REGISTRY}} REPOSITORY={{.REPOSITORY}} K8S_APP_NAME={{.K8S_APP_NAME}} APP_VERSION={{.APP_VERSION}} INFRA={{.INFRA}}

  nervo_migrant:
    taskfile: app.task.yml
    dir: nervo-migrant
    vars:
      K8S_APP_NAME: "nervo-migrant"
      APP_NAME: "nervo-migrant"
      CONFIGS: pvc.k job.k
      IMAGE_NAME:
        sh: task img_name REGISTRY={{.REGISTRY}} REPOSITORY={{.REPOSITORY}} K8S_APP_NAME={{.K8S_APP_NAME}} APP_VERSION={{.APP_VERSION}} INFRA={{.INFRA}}


tasks:
  default:
    cmds:
      - task --list-all
