version: '3'

set: [pipefail]

includes:
  nervoznyak:
    taskfile: app.task.yml
    dir: nervoznyak
    vars:
      USER: "{{.USER}}"
      K8S_APP_NAME: 'nervoznyak'
      APP_NAME: 'jarvis'
      CONFIGS: statefulset.k
      IMAGE_NAME:
        sh: task -t {{.ROOT_DIR}}/Taskfile.yml infra:k8s:img_name REGISTRY={{.REGISTRY}} REPOSITORY={{.REPOSITORY}} K8S_APP_NAME={{.APP_NAME}} APP_VERSION={{.APP_VERSION}} INFRA={{.INFRA}}

  nervo_server:
    taskfile: app.task.yml
    dir: nervo-server
    vars:
      USER: "{{.USER}}"
      K8S_APP_NAME: "nervo-server"
      APP_NAME: "nervo_server"
      CONFIGS: statefulset.k service.k ingress.k
      IMAGE_NAME:
        sh: task -t {{.ROOT_DIR}}/Taskfile.yml infra:k8s:img_name REGISTRY={{.REGISTRY}} REPOSITORY={{.REPOSITORY}} K8S_APP_NAME={{.K8S_APP_NAME}} APP_VERSION={{.APP_VERSION}} INFRA={{.INFRA}}

  nervo_migrant:
    taskfile: app.task.yml
    dir: nervo-migrant
    vars:
      USER: "{{.USER}}"
      K8S_APP_NAME: "nervo-migrant"
      APP_NAME: "nervo-migrant"
      CONFIGS: job.k
      IMAGE_NAME:
        sh: task -t {{.ROOT_DIR}}/Taskfile.yml infra:k8s:img_name REGISTRY={{.REGISTRY}} REPOSITORY={{.REPOSITORY}} K8S_APP_NAME={{.K8S_APP_NAME}} APP_VERSION={{.APP_VERSION}} INFRA={{.INFRA}}

  kevin:
    taskfile: app.task.yml
    dir: kevin
    vars:
      K8S_APP_NAME: 'kevin'
      APP_NAME: 'jarvis'
      CONFIGS: statefulset.k
      IMAGE_NAME:
        sh: task -t {{.ROOT_DIR}}/Taskfile.yml infra:k8s:img_name REGISTRY={{.REGISTRY}} REPOSITORY={{.REPOSITORY}} K8S_APP_NAME={{.APP_NAME}} APP_VERSION={{.APP_VERSION}} INFRA={{.INFRA}}

tasks:
  default:
    cmds:
      - task --list-all

  img_name:
    requires:
      vars:
        - REGISTRY
        - REPOSITORY
        - K8S_APP_NAME
        - APP_VERSION
        - INFRA
    vars:
      USER:
        sh: echo ${USER}
      IMG_NAME_PREFIX: '{{.REGISTRY}}/{{.REPOSITORY}}:{{.K8S_APP_NAME}}'
      IMG_NAME_PROD: '{{.IMG_NAME_PREFIX}}_v{{.APP_VERSION}}'
      IMG_NAME_DEV: "{{.IMG_NAME_PREFIX}}_{{.USER}}_dev_v{{.APP_VERSION}}"
    cmds:
      - echo {{if eq .INFRA "prod"}}{{.IMG_NAME_PROD}}{{else}}{{.IMG_NAME_DEV}}{{end}}