name: Docker setup

runs:
  using: "composite"
  steps:
    - name: Enable docker
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      shell: bash
      working-directory: infra
      run: devbox run 'task deployment:docker_registry:docker_login'
