name: Setup sccache

# https://github.com/orgs/community/discussions/26245#discussioncomment-5962450

runs:
  using: "composite"
  steps:
    - name: Set Rust caching env vars
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "SCCACHE_VERSION=v0.8.1" >> $GITHUB_ENV

    - name: Sccache Action
      uses: Mozilla-Actions/sccache-action@v0.0.5
      with:
        version: ${{ env.SCCACHE_VERSION }}
