name: Docker

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: enable docker
        uses: docker/setup-buildx-action@v3

      - name: install nix
        uses: cachix/install-nix-action@v25

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.8.0

      - name: Run Vault
        working-directory: infra/hazmat
        env:
          NERVOSET_VOID_SENTINEL: ${{ secrets.NERVOSET_VOID_SENTINEL }}
        run: |
          sudo chown -R 1000:1000 vault
          devbox run vault_full_run

      - name: Docker Login
        working-directory: infra
        run: |
          devbox run docker_login

      - name: Build and push docker image
        working-directory: nervoset
        run: |
          devbox run task docker_probiot_t1000_push
          devbox run task docker_r2d2_push
