name: Docker

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: enable docker
        uses: docker/setup-buildx-action@v3

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.8.0
        with:
          project-path: 'infra'
          enable-cache: 'true'

      - name: Run devbox shell
        working-directory: infra
        run: devbox shell

      - name: Run Vault
        working-directory: infra/hazmat
        env:
          NERVOSET_VOID_SENTINEL: ${{ secrets.NERVOSET_VOID_SENTINEL }}
        run: |
          task vault_full_run

      - name: Set Docker credentials
        working-directory: infra/hazmat
        run: |
          echo "DOCKER_USER_NAME=$(task vault_secret_docker_user)" >> $GITHUB_ENV
          echo "DOCKER_TOKEN=$(task vault_secret_docker_pass)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER_NAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Build and push docker image
        working-directory: nervoset
        run: |
          devbox run 'task docker_probiot_t1000_push'
          devbox run 'task docker_r2d2_push'
          devbox run 'task docker_groot_push'
