name: Docker Artifacts Deployment

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker_artifact.yml'
      - 'nervoset/app/**'

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  docker_deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: enable docker
        uses: docker/setup-buildx-action@v3

      - uses: ./.github/actions/devbox_setup
        with:
          devbox-path: 'infra'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        working-directory: nervoset
        run: |
          devbox run 'task docker_push INFRA=prod'
