name: Docker

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: enable docker
        uses: docker/setup-buildx-action@v3

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.8.0
        with:
          project-path: 'infra'
          enable-cache: 'true'

      - name: Run Vault
        working-directory: infra
        env:
          NERVOSET_VOID_SENTINEL: ${{ secrets.NERVOSET_VOID_SENTINEL }}
        run: |
          devbox run 'cd hazmat && task vault_full_run'

      - name: Login to Docker Hub
        working-directory: infra
        run: devbox run 'task kube:docker_login'

      - name: Build and push docker image
        working-directory: nervoset
        run: |
          devbox run 'task docker_probiot_t1000_push'
          devbox run 'task docker_r2d2_push'
          devbox run 'task docker_groot_push'
