name: Docker Artifacts Deployment

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker_artifact.yml'
      - 'nervoset/app/**'

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  docker_deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: enable docker
        uses: docker/setup-buildx-action@v3

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.8.0
        with:
          project-path: 'infra'
          enable-cache: 'true'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        working-directory: nervoset
        run: |
          devbox run 'task docker_groot:push INFRA=prod'
          devbox run 'task docker_probiot:push INFRA=prod'
          devbox run 'task docker_jarvis:push INFRA=prod'
          devbox run 'task docker_nervo_server:push INFRA=prod'
