name: Main Deployment

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - '.github/workflows/main.yml'
      - 'nervoset/**'
      - 'infra/**'

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  docker_hub_push:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/devbox_setup

      - uses: ./.github/actions/void_sentinel_auth
        with:
          main-password: ${{ secrets.NERVOSET_VOID_SENTINEL }}

      - uses: ./.github/actions/docker_setup

      - name: Build and push docker image
        run: devbox run task nervoset:docker_push INFRA=prod

  infra_deployment_test:
    timeout-minutes: 45
    needs: docker_hub_push

    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/devbox_setup

      - uses: ./.github/actions/void_sentinel_auth
        with:
          main-password: ${{ secrets.NERVOSET_VOID_SENTINEL }}

      - uses: ./.github/actions/docker_setup

      - name: deploying k8s infra
        run: devbox run task infra:deployment:infra_dev

