name: Build and Test

on:
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/devbox_setup
      with:
        devbox-path: 'nervoset'

    - uses: ./.github/actions/void_sentinel_auth
      with:
        main-password: ${{ secrets.NERVOSET_VOID_SENTINEL }}

    - uses: ./.github/actions/docker_setup

    - name: Run tests
      working-directory: nervoset
      run: devbox run task test
