name: Build and Test

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: nervoset/base:latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Task
      uses: arduino/setup-task@v2

    - name: Enable docker
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    #- uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
    #  continue-on-error: true

    #- name: Prepare dependencies
    #  working-directory: nervoset
    #  run: task prepare_dependencies

    # https://www.kenmuse.com/blog/implementing-docker-layer-caching-in-github-actions/
    #- name: Cache base docker image
    #  id: build-and-push
    #  uses: docker/build-push-action@v4
    #  with:
    #    context: ./nervoset
    #    file: ./nervoset/base.dockerfile
    #    push: true
    #    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    #    #tags: ${{ steps.meta.outputs.tags }}
    #    #cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    #    #cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},mode=max
    #    cache-from: type=gha
    #    cache-to: type=gha,mode=max

    - name: Sccache Action
      uses: Mozilla-Actions/sccache-action@v0.0.4
      with:
        version: "v0.7.7"

    - name: Set Rust caching env vars
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

    - name: Run tests
      working-directory: nervoset/app
      run: cargo test
