name: Build and Test

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Task
      uses: arduino/setup-task@v2

    - name: Sccache Action
      uses: Mozilla-Actions/sccache-action@v0.0.4
      with:
        version: "v0.7.7"

    - name: Set Rust caching env vars
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

    - name: Run tests
      working-directory: nervoset/app
      run: cargo test
