name: Build and Test

on:
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Task
      uses: arduino/setup-task@v2

    - uses: .github/workflows/actions/setup_sccache.yml

    - name: Run tests
      working-directory: nervoset/app
      run: cargo test

  deployment_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.8.0
        with:
          project-path: 'nervoset'
          enable-cache: 'true'
