name: Build and Test

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: enable docker
      uses: docker/setup-buildx-action@v3

    - name: install nix
      uses: cachix/install-nix-action@v25

    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Install devbox
      uses: jetpack-io/devbox-install-action@v0.8.0

    - name: Run tests
      working-directory: ./nervoset
      run: devbox run task docker_test
