name: Web Artifacts Deployment

on:
  workflow_dispatch:

#  push:
#    branches:
#      - main
#    paths:
#      - '.github/workflows/web_artifact.yml'
#      - 'nervoset/nervo-web/**'
#      - 'nervoset/app/nervo_wasm/**'

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Deploy nervo-web module on cdn (cloudflare pages)
  web_deployment:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    permissions:
      contents: read
      deployments: write
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source


    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/devbox_setup

      - uses: ./.github/actions/sccache_setup

      - uses: ./.github/actions/void_sentinel_auth
        with:
          main-password: ${{ secrets.NERVOSET_VOID_SENTINEL }}

      - uses: ./.github/actions/docker_setup

      - name: Set credentials
        run: |
          echo "CLOUD_FLARE_API_TOKEN=$(devbox run task infra:hazmat:void_sentinel:vault:get_cloudflare_api_token)" >> $GITHUB_ENV
          echo "CLOUD_FLARE_ACCOUNT_ID=$(devbox run task infra:hazmat:void_sentinel:vault:get_cloudflare_account_id)" >> $GITHUB_ENV
          echo "GH_TOKEN=$(devbox run task infra:hazmat:void_sentinel:vault:get_github_token)" >> $GITHUB_ENV

      ### Nervoznyak Deployment ###
      - name: Build nervo-web for nervoznyak
        run: devbox run task nervoset:nervo_web_build AGENT_TYPE=nervoznyak

      - name: Deploy nervo-web-nervoznyak on github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ env.GH_TOKEN }}
          external_repository: nervoset/nervo-web
          publish_branch: main
          publish_dir: nervoset/nervo-web/dist
          destination_dir: nervoznyak
