name: Web Artifacts Deployment

on:
  workflow_dispatch:

#  push:
#    branches:
#      - main
#    paths:
#      - '.github/workflows/web_artifact.yml'
#      - 'nervoset/nervo-web/**'
#      - 'nervoset/app/nervo_wasm/**'

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Deploy nervo-web module on cdn (cloudflare pages)
  web_deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/devbox_setup

      - uses: ./.github/actions/sccache_setup

      - uses: ./.github/actions/void_sentinel_auth
        with:
          main-password: ${{ secrets.NERVOSET_VOID_SENTINEL }}

      - uses: ./.github/actions/docker_setup

      - name: Set cloudflare credentials
        run: |
          echo "CLOUD_FLARE_API_TOKEN=$(devbox run task infra:hazmat:void_sentinel:vault:get_cloudflare_api_token)" >> $GITHUB_ENV
          echo "CLOUD_FLARE_ACCOUNT_ID=$(devbox run task infra:hazmat:void_sentinel:vault:get_cloudflare_account_id)" >> $GITHUB_ENV

      ### Probiot Deployment ###
      - name: Build nervo-web for probiot
        run: devbox run task nervoset:nervo_web_build AGENT_TYPE=probiot

      - name: Deploy nervo-web-probiot on cloudflare pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ env.CLOUD_FLARE_API_TOKEN }}
          accountId: ${{ env.CLOUD_FLARE_ACCOUNT_ID }}
          projectName: nervo-web-probiot
          directory: nervoset/nervo-web/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      ### W3a Deployment ###
      - name: Build nervo-web for w3a
        run: devbox run task nervoset:nervo_web_build AGENT_TYPE=w3a

      - name: Deploy nervo-web-w3a on cloudflare pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ env.CLOUD_FLARE_API_TOKEN }}
          accountId: ${{ env.CLOUD_FLARE_ACCOUNT_ID }}
          projectName: nervo-web-w3a
          directory: nervoset/nervo-web/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      ### Nervoznyak Deployment ###
      - name: Build nervo-web for nervoznyak
        run: devbox run task nervoset:nervo_web_build AGENT_TYPE=nervoznyak

      - name: Deploy nervo-web-nervoznyak on cloudflare pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ env.CLOUD_FLARE_API_TOKEN }}
          accountId: ${{ env.CLOUD_FLARE_ACCOUNT_ID }}
          projectName: nervo-web-nervoznyak
          directory: nervoset/nervo-web/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
